const types = {
  LOGIN_USER: "LOGIN_USER",
  SEND_BACKEND_LOGIN_ERRORS: "SEND_BACKEND_LOGIN_ERROR",
  CLEAR_BACKEND_LOGIN_ERRORS: "CLEAR_BACKEND_LOGIN_ERRORS",
  LOGOUT_USER: "LOGOUT_USER",
  CREATE_USER: "CREATE_USER",
  SEND_BACKEND_REGISTER_ERRORS: "SEND_BACKEND_REGISTER_ERRORS",
  CLEAR_BACKEND_REGISTER_ERRORS: "CLEAR_BACKEND_REGISTER_ERRORS",
  REFRESH_TOKEN: "REFRESH_TOKEN",
};

export default types;
