const types = {
  LOGIN_USER: "LOGIN_USER",
  SET_IS_LOGGING_IN: "SET_IS_LOGGING_IN",
  SEND_BACKEND_LOGIN_ERRORS: "SEND_BACKEND_LOGIN_ERROR",
  CLEAR_BACKEND_LOGIN_ERRORS: "CLEAR_BACKEND_LOGIN_ERRORS",
  LOGOUT_USER: "LOGOUT_USER",
  CREATE_USER: "CREATE_USER",
  SET_IS_CREATING_USER: "SET_IS_CREATING_USER",
  SEND_BACKEND_REGISTER_ERRORS: "SEND_BACKEND_REGISTER_ERRORS",
  CLEAR_BACKEND_REGISTER_ERRORS: "CLEAR_BACKEND_REGISTER_ERRORS",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  GET_CONTACTS: "GET_CONTACTS",
  SEND_GET_CONTACTS_ERRORS: "SEND_GET_CONTACTS_ERRORS",
  REMOVE_GET_CONTACTS_ERRORS: "REMOVE_GET_CONTACTS_ERRORS",
  GET_GROUPS: "GET_GROUPS",
  SEND_GET_GROUPS_ERRORS: "SEND_GET_GROUPS_ERRORS",
  REMOVE_GET_GROUPS_ERRORS: "REMOVE_GET_GROUPS_ERRORS",
};

export default types;
