@url=http://localhost:8080/api

POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
  "username":"jay@dev10.com",
  "password":"P@ssw0rd!"
}


###
POST {{url}}/create_account HTTP/1.1
Content-Type: application/json

{
  "username":"bill@dev10.com",
  "password":"P@ssw0rd!",
  "email": "bill@dev10.com",
  "phone":"2222222",
  "firstName": "Bill",
  "lastName":"Blase"
}

###

POST {{url}}/refresh_token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsZXRzLWdvIiwic3ViIjoiYXJpdEBkZXYxMC5jb20iLCJhcHBfdXNlcl9pZCI6MywiYXV0aG9yaXRpZXMiOiJVU0VSIiwiZXhwIjoxNjg4MTM3Mjk0fQ.5j10pHu-xCu5Rq5rajAULBA7FiK07sx6JqO8rEYqXTE


