@url=http://localhost:8080/api/event
@token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsZXRzLWdvIiwic3ViIjoiYXJpdEBkZXYxMC5jb20iLCJhcHBfdXNlcl9pZCI6MywiYXV0aG9yaXRpZXMiOiJVU0VSIiwiZXhwIjoxNjg4NTY0ODYyfQ._onvDaKuQzWvdlgrJ9rUBECOWJPD0IlJay3LDx8h_yQ

// FUNCTION: findEventById
// RETURNS: an Event
// PATH: /:eventId
// ACCESS: PUBLIC

GET {{url}}/6

###

// FUNCTION: findSavedEventForUser
// RETURNS: a SavedEvent (has groups and contacts attached)
// PATH: /user/:eventId/:appUserId
// ACCESS: AUTH

GET {{url}}/user/4/3 HTTP/1.1
Authorization:Bearer {{token}}

###

// FUNCTION: saveEventForUser
// RETURNS: an Event
// PATH: /user/:appUserId
// ACCESS: AUTH

POST {{url}}/user/3
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "eventId": 6,
  "eventName": "Davido",
  "category": null,
  "imageUrl": "https://seatgeek.com/images/performers-landscape/davido-e9c361/250876/45976/huge.jpg",
  "description": null,
  "dateTime": "2023-07-07T19:00:00",
  "source": "SeatGeek",
  "sourceId": "6008856",
  "eventLink": "https://seatgeek.com/davido-tickets/houston-texas-toyota-center-7-2023-07-07-7-pm/concert/6008856",
  "venue": {
    "venueId": 7,
    "venueName": "Toyota Center",
    "address": "1510 Polk Street",
    "city": "Houston",
    "state": "TX",
    "country": null,
    "zipCode": 77002,
    "events": []
  },
  "eventPosts": []
}

###

// FUNCTION: removeEventFromUser
// RETURNS: void
// PATH: /user/:eventId/:appUserId
// ACCESS: AUTH

DELETE {{url}}/user/6/3
Content-Type: application/json
Authorization:Bearer {{token}}





