@url=http://localhost:8080/api/event-post
@token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsZXRzLWdvIiwic3ViIjoiYXJpdEBkZXYxMC5jb20iLCJhcHBfdXNlcl9pZCI6MywiYXV0aG9yaXRpZXMiOiJVU0VSIiwiZXhwIjoxNjg4NjE1ODU4fQ.1WC56P-Z5qj3Y3eUgKpmNe4uLG-CGSNLJ0gyl1YAIrA

###

// FUNCTION: findPostsByEventId
// RETURNS: List of EventPosts
// PATH: /:eventId
// ACCESS: PUBLIC

GET {{url}}/1

###

// FUNCTION: findPostById
// RETURNS: an EventPost
// PATH: /:eventPostId;
// ACCESS: PUBLIC

GET {{url}}/post/1

###

// FUNCTION: createEventPost
// RETURNS: an EventPost
// PATH: /
// ACCESS: AUTH

POST {{url}}
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "eventId": 1,
  "appUserId": 1,
  "author": "eric@dev10.com",
  "postDate": "2015-08-10T19:00:00",
  "postBody": "Did you find cheaper tickets elsewhere?",
  "likes": 1
}

###

// FUNCTION: updateEventPost
// RETURNS: an EventPost
// PATH: /:eventPostId
// ACCESS: AUTH

PUT {{url}}/6
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "postId":6,
  "eventId": 1,
  "appUserId": 1,
  "author": "eric@dev10.com",
  "postDate": "2015-08-10T19:00:00",
  "postBody": "Did you find cheaper from anyone around?",
  "likes": 1
}

###

// FUNCTION: deleteEventPost
// RETURNS: void
// PATH: /:eventPostId
// ACCESS: AUTH

DELETE {{url}}/7
Content-Type: application/json
Authorization:Bearer {{token}}






