@url=http://localhost:8080/api/venue

@token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsZXRzLWdvIiwic3ViIjoiZXJpY0BkZXYxMC5jb20iLCJhcHBfdXNlcl9pZCI6MSwiYXV0aG9yaXRpZXMiOiJVU0VSIiwiZXhwIjoxNjg4MTc5OTQwfQ.Q2n_0dzZOWfQgZeez9pPrDjOURly0_kTiR0vrusQfKY

// FUNCTION: findAllVenues
// RETURNS: List of Venues
// PATH: /
// ACCESS: PUBLIC

GET {{url}}

###

// FUNCTION: findVenueById
// RETURNS: a Venue
// PATH: /:venueId
// ACCESS: PUBLIC

GET {{url}}/1

###

// FUNCTION: upsertVenue
// RETURNS: a Venue
// PATH: /
// ACCESS: AUTH

POST {{url}}
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "venueName": "The Wine Cellar",
  "address": "2222 Fifth St.",
  "city": "New York",
  "state": "NY",
  "country": "United States",
  "zipCode": 29292
}

###

// FUNCTION: updateVenue
// RETURNS: a Venue
// PATH: /:venueId
// ACCESS: AUTH

PUT {{url}}/4
Content-Type: application/json
Authorization:Bearer {{token}}

{
    "venueId": 4,
    "venueName": "The Quack Shack",
    "address": "2452 10th St.",
    "city": "Chicago",
    "state": "IL",
    "country": "United States",
    "zipCode": 56748
}
